apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus # referenced by uid from the dashboard JSON
    type: prometheus
    access: proxy
    url: http://events-prometheus:9090
    isDefault: true
